spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/banklineapi_db?useTimeZone=true&serverTimeZone=UTC&useLegacyDate
    username: postgres
    password: 930730Jf
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate.format_sql: true
